const assert = require('assert')

try {

} catch (error) {
    console.log(error);
}